import { Article } from "components/Article";
import { Props } from "components/types";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage<Props> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Article articles={props.articles} />
    </div>
  );
};

export const getStaticProps = async () => {
  const pageSize = 10;
  const topRes = await fetch(
    `https://newsapi.org/v2/top-headlines?country=jp&pageSize=${pageSize}&apiKey=${process.env.NEWS_API_KEY}`
  );
  const json = await topRes.json();
  const articles = json.articles;
  console.log(articles);
  
  return {
    props: {
      articles,
    },
    revalidate: 60 * 10,
  };
};

export default Home;
