import { Article } from "components/Article";
import { Props } from "components/types";
import type { NextPage } from "next";
import Head from "next/head";
import { newsApi } from "libs/news";
import { Weather } from "components/Weather";
import { Grid } from "@mantine/core";

const Home: NextPage<Props> = ({ articles, weather }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid gutter="xl">
        <Grid.Col span={9}>
          <Article articles={articles} title="Top Stories" />
        </Grid.Col>
        <Grid.Col span={3}>
          <Weather weather={weather} />
        </Grid.Col>
      </Grid>
    </div>
  );
};

export const getStaticProps = async () => {
  const newsData = await newsApi.v2.topHeadlines({
    country: "jp",
  });

  const exclude = "hourly,minutely";
  const weatherRes = await fetch(
    `https://api.openweathermap.org/data/2.5/onecall?lat=${process.env.LAT}&lon=${process.env.LON}&units=metric&exclude=${exclude}&appid=${process.env.WEATHER_API_KEY}`
  );
  const weatherData = await weatherRes.json();
  console.log(weatherData.current);

  return {
    props: {
      articles: newsData.articles,
      weather: weatherData,
    },
    revalidate: 60 * 10,
  };
};
export default Home;
